name: Test
on: push
jobs:
  test-without-tests-arg:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Run unit tests
      uses: ./
      with:
        src: tests